services:
  app:
    image: thaitvdhe153071/photo-sharing-app:latest
    container_name: laravel_app
    restart: unless-stopped
    volumes:
      - ./storage:/var/www/storage
      - ./public:/var/www/public
    networks:
      - laravel

  web:
    image: nginx:alpine
    container_name: laravel_web
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./storage:/var/www/storage
      - ./public:/var/www/public
    depends_on:
      - app
    networks:
      - laravel

  db:
    image: mysql:8.0
    container_name: laravel_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: photo-sharing-app-db
      MYSQL_ROOT_PASSWORD: rootsecret
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel

networks:
  laravel:

volumes:
  db_data:
